const tools=[
{id:'squat',name:'Squat Effect',desc:'Açık ve kısıtlı sularda Barrass hızlı tahmini.',fields:[['lpp','LPP (m)',196.8],['beam','Breadth (m)',32.26],['disp','Deplasman (t)',29361.7],['density','Yoğunluk (t/m³)',1.018],['draft','Draft (m)',6.93]],calc:v=>{const vd=v.disp/v.density,cb=vd/(v.lpp*v.beam*v.draft),rows=[];for(let s=1;s<=20;s++)rows.push([s,cb*s*s/100,cb*s*s/50]);return{metrics:[['VD',vd.toFixed(1)+' m³'],['Cb',cb.toFixed(3)],['Maks. squat bölgesi',cb>.7?'Baş tarafı':'Kıç tarafı']],table:['Sürat (kn)','Açık su (m)','Kısıtlı su (m)',rows],note:'Cb > 0,70 için maksimum squat çoğunlukla başta; Cb < 0,70 için çoğunlukla kıçta görülür. Manevra kitapçığını kontrol edin.'}}},
{id:'ukc',name:'UKC',desc:'Statik ve dinamik omurga altı açıklığı.',fields:[['depth','Harita/ölçülen derinlik (m)',12],['tide','Gelgit yüksekliği (m)',1.2],['draft','Azami draft (m)',8],['squat','Squat (m)',0.6],['heel','Yatma payı (m)',0.2],['safety','Emniyet payı (m)',1]],calc:v=>{const available=v.depth+v.tide-v.draft-v.squat-v.heel,margin=available-v.safety;return{metrics:[['Dinamik UKC',available.toFixed(2)+' m'],['Emniyet payı sonrası',margin.toFixed(2)+' m'],['Durum',margin>=0?'UYGUN':'YETERSİZ']],note:'Derinlik datumları, gelgit düzeltmesi, trim, hog/sag, dalga tepki payı ve şirket UKC politikası ayrıca değerlendirilmelidir.'}}},
{id:'eta',name:'ETA / Seyir',desc:'Mesafe, sürat, süre ve varış zamanı.',fields:[['distance','Mesafe (NM)',120],['speed','Ortalama sürat (kn)',12],['delay','Bekleme/gecikme (dk)',0]],calc:v=>{const h=v.distance/v.speed+v.delay/60,eta=new Date(Date.now()+h*3600000);return{metrics:[['Seyir süresi',fmtHours(h)],['ETA',eta.toLocaleString('tr-TR')],['Ortalama hız',v.speed.toFixed(1)+' kn']]}}},
{id:'cpa',name:'CPA / TCPA',desc:'İki geminin bağıl hareket hesabı.',fields:[['range','Hedef mesafesi (NM)',6],['bearing','Hedef kerterizi (°)',45],['ownC','Kendi rotası (°)',0],['ownS','Kendi sürati (kn)',12],['tarC','Hedef rotası (°)',270],['tarS','Hedef sürati (kn)',10]],calc:v=>{const r=vec(v.range,v.bearing),ov=vec(v.ownS,v.ownC),tv=vec(v.tarS,v.tarC),rv={x:tv.x-ov.x,y:tv.y-ov.y},vv=rv.x*rv.x+rv.y*rv.y;let t=vv?-(r.x*rv.x+r.y*rv.y)/vv:0;t=Math.max(0,t);const c={x:r.x+rv.x*t,y:r.y+rv.y*t},cpa=Math.hypot(c.x,c.y);return{metrics:[['CPA',cpa.toFixed(2)+' NM'],['TCPA',fmtHours(t)],['Bağıl sürat',Math.sqrt(vv).toFixed(1)+' kn']],note:'Kerterizler gerçek kuzeye göre derece kabul edilmiştir. Radar/ARPA verileri ve manevra niyetiyle doğrulayın.'}}},
{id:'wheel',name:'Wheel Over',desc:'Dönüş yarıçapı ve rota değişimine göre wheel-over mesafesi.',fields:[['radius','Dönüş yarıçapı (NM)',0.5],['alter','Rota değişimi (°)',60],['advance','Köprüüstü tepki payı (NM)',0.1]],calc:v=>{const d=v.radius*Math.tan(rad(Math.min(179,Math.abs(v.alter)))/2)+v.advance;return{metrics:[['Wheel-over mesafesi',d.toFixed(2)+' NM'],['Rota değişimi',Math.abs(v.alter).toFixed(0)+'°'],['Yarıçap',v.radius.toFixed(2)+' NM']],note:'Bu geometrik hızlı tahmindir. Gerçek advance/transfer değerleri geminin manevra kitapçığından alınmalıdır.'}}},
{id:'turn',name:'Dönüş Dairesi',desc:'LOA katsayılarıyla advance, transfer ve çap tahmini.',fields:[['loa','LOA (m)',200],['advanceK','Advance / LOA',4.5],['transferK','Transfer / LOA',2.5],['diamK','Taktik çap / LOA',5]],calc:v=>({metrics:[['Advance',(v.loa*v.advanceK).toFixed(0)+' m'],['Transfer',(v.loa*v.transferK).toFixed(0)+' m'],['Taktik çap',(v.loa*v.diamK).toFixed(0)+' m']]} )},
{id:'stop',name:'Durma Mesafesi',desc:'Sürat ve gemi boyuna göre hızlı durma tahmini.',fields:[['speed','Başlangıç sürati (kn)',14],['loa','LOA (m)',200],['factor','Durma katsayısı',6]],calc:v=>{const scale=Math.pow(v.speed/15,2),d=v.loa*v.factor*scale,t=d/(v.speed*.514444)/60;return{metrics:[['Durma mesafesi',d.toFixed(0)+' m'],['Yaklaşık süre',t.toFixed(1)+' dk'],['Gemi boyu',v.loa.toFixed(0)+' m']],note:'Makine tipi, yük, trim, rüzgâr, akıntı ve sığ su etkileri sonucu ciddi biçimde değiştirir.'}}},
{id:'tide',name:'Gelgit Yüksekliği',desc:'İki bilinen zaman arasında doğrusal ara değer.',fields:[['h1','İlk yükseklik (m)',0.4],['h2','Son yükseklik (m)',3.2],['elapsed','Geçen süre (dk)',180],['total','Toplam aralık (dk)',360]],calc:v=>{const f=Math.max(0,Math.min(1,v.elapsed/v.total)),h=v.h1+(v.h2-v.h1)*f;return{metrics:[['Tahmini yükseklik',h.toFixed(2)+' m'],['Aralık yüzdesi',(f*100).toFixed(0)+'%'],['Değişim',(h-v.h1).toFixed(2)+' m']],note:'Bu doğrusal ara değerdir. Standart limanlarda Rule of Twelfths veya resmi gelgit eğrileri daha uygun olabilir.'}}},
{id:'stream',name:'Akıntı / Drift',desc:'Set ve drift vektörünü gemi hareketine ekler.',fields:[['course','Geminin suya göre rotası (°)',90],['speed','Suya göre sürat (kn)',12],['set','Akıntı seti (°)',180],['drift','Akıntı sürati (kn)',2]],calc:v=>{const a=vec(v.speed,v.course),b=vec(v.drift,v.set),g={x:a.x+b.x,y:a.y+b.y};return{metrics:[['COG',bearing(g).toFixed(1)+'°'],['SOG',Math.hypot(g.x,g.y).toFixed(2)+' kn'],['Yatma açısı',angleDiff(bearing(g),v.course).toFixed(1)+'°']]}}},
{id:'safe',name:'Emniyetli Sürat',desc:'Görüş ve durma mesafesine göre eğitim amaçlı limit.',fields:[['visibility','Kullanılabilir görüş (NM)',2],['reaction','Tepki süresi (dk)',1],['stop','Durma mesafesi katsayısı (NM/kn²)',0.004]],calc:v=>{const a=v.stop,b=v.reaction/60,c=-v.visibility;const s=(-b+Math.sqrt(b*b-4*a*c))/(2*a);return{metrics:[['Tahmini azami sürat',s.toFixed(1)+' kn'],['Görüş',v.visibility.toFixed(1)+' NM'],['Tepki süresi',v.reaction.toFixed(1)+' dk']],note:'COLREG Kural 6 kapsamındaki trafik, manevra kabiliyeti, gece ışıkları, deniz durumu ve radar kısıtları ayrıca değerlendirilir.'}}},
{id:'pi',name:'Parallel Index',desc:'Planlanan hat ile tehlike arasındaki radar PI mesafesi.',fields:[['distance','Tehlikenin rota hattına dik mesafesi (NM)',0.8],['safety','İstenen ilave emniyet (NM)',0.2]],calc:v=>({metrics:[['PI mesafesi',(v.distance+v.safety).toFixed(2)+' NM'],['Temel mesafe',v.distance.toFixed(2)+' NM'],['Emniyet ilavesi',v.safety.toFixed(2)+' NM']]})},
{id:'anchor',name:'Demirleme',desc:'Su derinliği ve friborda göre zincir boyu.',fields:[['depth','Su derinliği (m)',20],['freeboard','Hawse yüksekliği (m)',5],['scope','Scope oranı',5]],calc:v=>{const vertical=v.depth+v.freeboard,len=vertical*v.scope;return{metrics:[['Önerilen zincir',len.toFixed(0)+' m'],['Yaklaşık kilit', (len/27.5).toFixed(1)],['Düşey mesafe',vertical.toFixed(1)+' m']],note:'Hava, dip yapısı, akıntı, bekleme süresi ve demirleme alanı sınırlarına göre scope değiştirilmelidir.'}}},
{id:'air',name:'Air Draft',desc:'Köprü/hat altı düşey açıklık kontrolü.',fields:[['clearance','Yayınlanan açıklık (m)',45],['tide','Su seviyesi düzeltmesi (m)',1.2],['airdraft','Gemi air draftı (m)',40],['safety','Emniyet payı (m)',2]],calc:v=>{const net=v.clearance-v.tide-v.airdraft,margin=net-v.safety;return{metrics:[['Net açıklık',net.toFixed(2)+' m'],['Emniyet sonrası',margin.toFixed(2)+' m'],['Durum',margin>=0?'UYGUN':'YETERSİZ']]}}},
{id:'pivot',name:'Pivot Point',desc:'İleri/tornistan durumunda yaklaşık pivot noktası.',fields:[['loa','LOA (m)',200],['mode','İleri=1, duruş=0, tornistan=-1',1]],calc:v=>{const pos=v.mode>0?v.loa*.25:v.mode<0?v.loa*.75:v.loa*.5;return{metrics:[['Baştan mesafe',pos.toFixed(0)+' m'],['LOA yüzdesi',(pos/v.loa*100).toFixed(0)+'%'],['Durum',v.mode>0?'İleri hareket':v.mode<0?'Tornistan':'Duruş']],note:'Pivot noktası sürat, ivme, dümen, rüzgâr ve yanal hareketle sürekli değişir.'}}},
{id:'wind',name:'Rüzgâr Düzeltmesi',desc:'Crosswind için yaklaşık crab açısı.',fields:[['tas','Gemi sürati (kn)',12],['wind','Rüzgâr hızı (kn)',20],['angle','Rüzgârın rota ile açısı (°)',90],['factor','Etki katsayısı',0.08]],calc:v=>{const cross=v.wind*Math.sin(rad(v.angle))*v.factor,ang=Math.asin(Math.max(-.99,Math.min(.99,cross/v.tas)));return{metrics:[['Düzeltme açısı',Math.abs(ang*180/Math.PI).toFixed(1)+'°'],['Yanal etki',cross.toFixed(2)+' kn'],['Öneri',ang>=0?'Rüzgâra doğru düzelt':'Ters yöne düzelt']],note:'Etki katsayısı geminin rüzgâr alanı ve yük durumuna göre kalibre edilmelidir.'}}},
{id:'fuel',name:'Yakıt Tüketimi',desc:'Seyir süresi, günlük tüketim ve rezerv hesabı.',fields:[['distance','Mesafe (NM)',500],['speed','Sürat (kn)',12],['daily','Günlük tüketim (t/gün)',24],['reserve','Rezerv (%)',15]],calc:v=>{const days=v.distance/v.speed/24,base=days*v.daily,total=base*(1+v.reserve/100);return{metrics:[['Seyir süresi',fmtHours(days*24)],['Temel tüketim',base.toFixed(2)+' t'],['Rezervli ihtiyaç',total.toFixed(2)+' t']]}}}
];
const nav=document.querySelector('#toolNav'),root=document.querySelector('#calculator');
const parse=x=>Number(String(x).replace(',','.'))||0,rad=d=>d*Math.PI/180;
function vec(m,b){const r=rad(b);return{x:m*Math.sin(r),y:m*Math.cos(r)}}
function bearing(v){return(Math.atan2(v.x,v.y)*180/Math.PI+360)%360}
function angleDiff(a,b){return((a-b+540)%360)-180}
function fmtHours(h){const hr=Math.floor(h),m=Math.round((h-hr)*60);return`${hr} sa ${m} dk`}
function render(tool){nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.id===tool.id));root.innerHTML=`<div class="calc-head"><div><h3>${tool.name}</h3><p>${tool.desc}</p></div><span class="tag">OFFLINE HESAPLAMA</span></div><form id="calcForm"><div class="fields">${tool.fields.map(([id,label,val])=>`<label class="field"><span>${label}</span><input name="${id}" value="${val}" inputmode="decimal" required></label>`).join('')}</div><div class="actions"><button class="primary" type="submit">HESAPLA</button><button class="ghost clear" type="reset">TEMİZLE</button></div></form><div id="result" class="result">Değerleri girip hesaplayın.</div>`;const form=root.querySelector('form'),out=root.querySelector('#result');const run=()=>{const v={};tool.fields.forEach(([id])=>v[id]=parse(form.elements[id].value));try{const r=tool.calc(v);out.innerHTML=resultHtml(r)}catch(e){out.innerHTML=`<span class="danger">Hesaplama yapılamadı. Girişleri kontrol edin.</span>`}};form.addEventListener('submit',e=>{e.preventDefault();run();save(tool.id,form)});form.addEventListener('reset',()=>setTimeout(()=>out.textContent='Değerleri girip hesaplayın.',0));load(tool.id,form);run()}
function resultHtml(r){let h='';if(r.metrics)h+=`<div class="metrics">${r.metrics.map(x=>`<div class="metric"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>`;if(r.table){const [a,b,c,rows]=r.table;h+=`<div class="table-wrap"><table><thead><tr><th>${a}</th><th>${b}</th><th>${c}</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x[0]}</td><td>${x[1].toFixed(2)}</td><td>${x[2].toFixed(2)}</td></tr>`).join('')}</tbody></table></div>`}if(r.note)h+=`<p class="note">${r.note}</p>`;return h}
function save(id,form){const d={};new FormData(form).forEach((v,k)=>d[k]=v);localStorage.setItem('mariner-tool-'+id,JSON.stringify(d))}
function load(id,form){try{const d=JSON.parse(localStorage.getItem('mariner-tool-'+id));if(d)Object.entries(d).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v})}catch{}}
tools.forEach((t,i)=>{const b=document.createElement('button');b.className='tool-tab'+(i?'':' active');b.dataset.id=t.id;b.textContent=t.name;b.onclick=()=>render(t);nav.appendChild(b)});render(tools[0]);document.querySelector('#printButton').onclick=()=>window.print();
